spring:
  application:
    name: employee-api

server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always

app:
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    root: INFO
    com.udap.platform.employeeapi: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} - %msg%n"
